### ISSUE TITLE
Circle-enrich-filter compatible with multiple reference genome

### ISSUE THREAD

**Issue by madagiurgiu25** [henssen-lab/circle-enrich-filter#2]
For the mitochondrial genome there are different annotation `chrM` or `MT` depending on the genome versions. 
Also, depending on the genome versions different scaffolds and patches annotations are included (which should be ignored).
Here we harmonise the pipeline for different human assemblies.

TODO: 
- Make circle-enrich-filter compatible with different human genome assemblies, i.e. hg19,  hg38 and hs37d5
- Ignore further non-primary chromosomes from processing e.g. "_alt", "_random"

**Comment by madagiurgiu25** [comment]
The pipeline should be now compatible with human (`GRCh38.p13`, `GRCh37.p13`, `hs37d5`, `hg38`, `hg19`) and mouse (`GRCm38`), i.e it accepts both mito annotations and excludes all annotations of patches and scaffolds which are not primary chromosomes. In case you analyse PDX samples please annotate your mouse genome with `"m.*"`, e.g. `m.1` or `m.chr1`.

**Comment by madagiurgiu25** [comment]
15b0bef

**Comment by xurob** [comment]
> 

keep in mind that different genome versions contain different MT assemblies. hs37d5 is hg19 with a rCRS mito genome, while hg19 has its own mito genome. hg38 uses rCRS
